import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms'; // To add employee
import { Router } from '@angular/router'; // To add emp
import { EmployeeService } from 'src/app/services/employee.service';
import { Employee } from 'src/app/models/employee.interface';
import { ErrorResponse } from 'src/app/models/error-response.interface';


@Component({
  selector: 'app-employee-form',
  templateUrl: './employee-form.component.html',
  styleUrls: ['./employee-form.component.scss']
})
export class EmployeeFormComponent {

  employeeForm: FormGroup;
  submitting = false;
  apiGeneralError = '';
  apiSuccessMessage = '';

  constructor( private fb : FormBuilder, private employeeService:  EmployeeService,  private router: Router
  ){
    this.employeeForm = this.fb.group({

      empName:[
        '',
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(100)
        ]
      ],

      empDesignation: [
        '',
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(100)
        ]
      ],

      empSalary: [
        null,
        [
          Validators.required,
          Validators.min(0),
        ]
      ],

      empExperienceYears:[
        null,
        [
          Validators.required,
          Validators.min(0),
          Validators.max(50)
        ]
      ],

      empPerformanceRating:[
        null,
        [
          Validators.required,
          Validators.min(1),
          Validators.max(5)
        ]
      ]
    }

    );
    console.log('Employee-Form-Component initilized');
    console.log('Form controls: ', this.employeeForm.controls); // all input entered will be seen in logs

  }

  //Get form

  get form() {
    return this.employeeForm.controls;
  }

  //

  submitForm(){

    console.log('submitForm() called');
    console.log('Form valid: ', this.employeeForm.valid); // it will log the status if data is valid
    console.log('Form value: ', this.employeeForm.value); // The current value of the control in an array
    console.log('Form errors: ', this.employeeForm.errors); // An object containing any errors generated by failing validation, or null if there
    console.log('Touched fields: ', Object.keys(this.form).filter((key) => this.form[key].touched )); // it will log the touched fields

    this.apiGeneralError = '';

    this.apiSuccessMessage = '';

    //if validator fails 

    if(this.employeeForm.invalid){
      console.log('Form is invalid , marking all fields as touched to show errors!');
      this.employeeForm.markAllAsTouched();
      return;
    }
    this.submitting = true; // submit this 

    const payLoad:  Employee =  this.employeeForm.value;
    console.log('Sending payload to employeeService: ', payLoad);
    this.employeeService.createEmployee(payLoad).subscribe(
      {
        next: (response) => {

          this.submitting = false;
          this.apiSuccessMessage = response.message || 'Employee created successfully!'
          console.log('Employee created successfully, response: ', response);
          console.log('Navigating to /employees list');
 
          //redirect to employeeList
          this.router.navigate(['/employees']);
        },
        error: (error: ErrorResponse) =>  {
          this.submitting = false;
          this.apiGeneralError = error.errorMessage || 'Failed to create employee';
          console.error('API error response: ', error); 

          if(error.errors){
            console.error('Field specific validation errors: ', error.errors);

            Object.keys(error.errors).forEach( fieldName => 
              {
               const formControl= this.employeeForm.get(fieldName);
               if(formControl){
                formControl.setErrors({
                apiError: error.errors?.[fieldName]
               });
               formControl.markAsTouched();
               console.log(`set API error on ${fieldName}: `, error.errors?.[fieldName]);
              }
            });

          }
        },
        //
        complete: () => {
          console.log('Create employee request call completed');

        },

      });
  }
}
